### ISSUE TITLE
Add registry settings for separate scroll bindings

### ISSUE THREAD

**Issue by wheeliemonster** [fredemmott/HTCC#27]
Add registry settings to bind separate 'scroll up/scroll down' buttons, instead of 'emulate 3-button point ctrl'

**Comment by fredemmott** [comment]
I'll probably split out the pointctrl button handling as a generic 3-to-4 handler; some people have issues with the oculus ring finger pinch being confused with the middle finger pinch - supporting either 3 or 4 'buttons' regardless of input method would be useful.

**Comment by fredemmott** [comment]
Done in 851a99ec6e053203a39a6fdc564c59f317cc5867 for v1.1
