### ISSUE TITLE
Feature Request - Pointer Stabilization

### ISSUE THREAD

**Issue by Rolln-dev** [fredemmott/HTCC#64]
Hi,

First off just wanted to comment on how much better of an experience this is in DCS than using the built in hand tracking.

I'm using a Leap Motion Controller with a Reverb G2.

Is it possible at all to add some sort of stabilization for the pointer?  Between your head slightly shaking and your hands slightly shaking it can sometimes be difficult to get the pointer on the buttons long enough to do the pinch gesture.

**Comment by fredemmott** [comment]
Been playing around this:
- feels unneeded for controller emulation
- not really possible for touch screen emulation: as this is based on a 2D pointer relative to your head, it needs to compensate for head movement, which requires depth information which is not available from the game.

#44 would effectively solve this problem without smoothing/stabilization.
