### ISSUE TITLE
HTCC + UltraLeap DCS World Head Movement Disorientation

### ISSUE THREAD

**Issue by KenR001** [fredemmott/HTCC#74]
I have HTCC working with my Leap Motion Controller 2 and a finger mouse. It works well but sometimes when I try to operate cockpit controls moving my head slightly causes my cursor to move in the opposite direction. Then my hand and head start fighting for control lol! When looking to the left cursor moves right. Hand tracking is perfect if I don't move my head, the cursor goes where I point. Is it possible to couple the two trackers together so the cursor stays where I point when moving my head? Maybe I have a configuration parameter setup incorrectly? Thanks.

![image](https://github.com/fredemmott/HTCC/assets/167020061/6a8d62fe-1e0d-4e2b-b532-8ed98e7ab0c5)

**Comment by fredemmott** [comment]
No, this is an inherent part of how DCS handles mouse and VR input. You probably want to pause HTCC by holding your hand near the top of your field of view until you hear beeps
