### ISSUE TITLE
DCS not showing hand with HTCC enable

### ISSUE THREAD

**Issue by taxsimsec** [fredemmott/HTCC#76]
When I enable HTCC, DCS doesn't show my hands. But if HTCC is disable, my hands are correctly showing in DCS. I don't understand why.

Headset : QUEST3
DCS version : 2.9
HTCC version : 1.0.0

**Comment by fredemmott** [comment]
This is expected:
- if you follow the recommended set up, your hands are used as a mouse pointer instead of DCS seeing hands
- if you instead follow the instructions for using oculus controller emulation, these instructions include making the hands invisble
